# Generated by Django 3.2 on 2021-07-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210625_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profilo', 'verbose_name_plural': 'Profili'},
        ),
    ]
